/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
plugins {
  java
  id("com.github.johnrengelman.shadow") version "7.1.2" //https://github.com/johnrengelman/shadow
}

repositories {
  maven { url = uri("https://maven.aliyun.com/nexus/content/groups/public") }
  maven { url = uri("https://jitpack.io") }
}

group = "io.gh"
version = "1.0"
java {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8
}

sourceSets {
  main {
    java {
      setSrcDirs(listOf("source/java")) //set
      srcDir("source/java")
    }
    resources {
      srcDir("config")
    }
  }
}

dependencies {
  implementation("com.gitee.jd-platform-opensource:asyncTool:V1.4-SNAPSHOT")
  implementation("org.jsoup:jsoup:1.15.3")
}

tasks {
  jar {
    manifest {
      attributes["Main-Class"] = "io.gh.hosts.Main"
    }
  }
}
